In [1]:
from sqlalchemy import (
    Boolean,
    Column,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    text,
    update,
)

from egowam.utils.aws.aws_sql import (
    TableRow,
    create_default_engine,
    episode_table_to_df,
)

In [2]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [3]:
df = episode_table_to_df(engine)

**Schema note:** Dataset locations use `processed_path` and `mp4_path`. Older DBs may lack `zarr_processing_error`; `episode_table_to_df()` adds it as empty if missing. Run `python egowam/utils/aws/migrate_add_zarr_columns.py` to add that column in Postgres if needed.

In [4]:
df

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
0,696bc6351cafc9f413b5b7e8,695d098f83a9fdf2d84d9a47,mecka,1960.0,packaging_cloths,"In the final part of the video, the person con...",stockroom,"[""plaid_cloths"", ""plastic_bags"", ""cardboard_bo...",NaN,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bc635...,,s3://rldb/processed_v3/mecka/freeform/696bc635...,NaN,None
1,696b2152d1aa1f60b4db5ef1,694a6ead5c0479a0fb867619,mecka,2700.0,cleaning_engine_parts,"A mechanic continues to clean a used, three-cy...",service_bay,"[""engine_gasket"", ""workbench"", ""cloth""]",NaN,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b2152...,,s3://rldb/processed_v3/mecka/freeform/696b2152...,NaN,None
2,696bcb732a9a68766920de81,696452cf83a9fdf2d86552c5,mecka,2252.0,folding_paper_bags,"A person begins folding a new paper bag, caref...",packaging_area,"[""paper_sheet"", ""glue"", ""plastic_container"", ""...",NaN,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,,s3://rldb/processed_v3/mecka/freeform/696bcb73...,NaN,None
3,69b4944484179943aec080c6,6948bbeb5c0479a0fb82ec42,mecka,2278.0,planting_cuttings,Planting plant cuttings into a tray filled wit...,nursery,"[""soil"", ""plant_cuttings"", ""tray"", ""pots""]",NaN,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/69b49444...,,s3://rldb/processed_v3/mecka/freeform/69b49444...,CC BY-SA 4.0,"[{'label': 'adjust soil in container', 'end_se..."
4,693cd014bec8abdc94f9a365,693369d4c195d3a38a24af5c,mecka,2650.0,labeling_eggs,The person uses a pair of scissors to cut labe...,packing_shed,"[""labels"", ""egg_cartons"", ""eggs""]",NaN,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/693cd014...,,s3://rldb/processed_v3/mecka/freeform/693cd014...,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72259,696db125ddefc568d7372680,695b04fc83a9fdf2d8485831,mecka,2698.0,packaging_items,"A person is sitting and packaging small, black...",material_storage,"[""air_stones"", ""plastic_bags"", ""cardboard_box""...",s3://rldb/mecka/freeform/696db125ddefc568d7372680,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696db125...,,s3://rldb/processed_v3/mecka/freeform/696db125...,CC BY-SA 4.0,"[{'label': 'pick up plastic bag, pick up grey ..."
72260,696b9a50a04610abd4bb2ed0,694901865c0479a0fb833c40,mecka,2848.0,decorating_party_horns,A person attaches a pre-made blue fringed pape...,craft_section,"[""party_horn"", ""blue_fringed_paper"", ""white_fr...",s3://rldb/mecka/freeform/696b9a50a04610abd4bb2ed0,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,,s3://rldb/processed_v3/mecka/freeform/696b9a50...,CC BY-SA 4.0,"[{'label': 'wrap fringe, adjust cone', 'end_se..."
72261,696bac1d7e6f94bf3414388d,6951c933c0d9448524bb1d46,mecka,3598.0,making_kites,A person continues to assemble a kite frame. T...,craft_section,"[""kite_frame"", ""bamboo_sticks"", ""string""]",s3://rldb/mecka/freeform/696bac1d7e6f94bf3414388d,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,,s3://rldb/processed_v3/mecka/freeform/696bac1d...,CC BY-SA 4.0,[{'label': 'tie two wooden sticks to form a cr...
72262,696babf5b17075c2c32fa74b,694c877362d08e8cd95f46fd,mecka,3598.0,cleaning_shoes,A person is using a brush and soapy water to s...,repair_bench,"[""shoe"", ""soapy_water""]",s3://rldb/mecka/freeform/696babf5b17075c2c32fa74b,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696babf5...,,s3://rldb/processed_v3/mecka/freeform/696babf5...,CC BY-SA 4.0,"[{'label': 'hold shoe, scrub shoe with brush',..."
72263,696bbd5575020a567fd376e9,6959d51cb8d0e4dc08fb48e1,mecka,3202.0,wick_preparation,"The person continues preparing candle wicks, c...",production_area,"[""tealight_cup"", ""wooden_sticks"", ""wick"", ""met...",s3://rldb/mecka/freeform/696bbd5575020a567fd376e9,NaN,...,mecka_bimanual,False,-1.0,True,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,,s3://rldb/processed_v3/mecka/freeform/696bbd55...,CC BY-SA 4.0,"[{'label': 'pick up sticks, align sticks', 'en..."

In [5]:
df[df["episode_hash"] == "2026-03-07-01-40-32-000000"]

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
27556,2026-03-07-01-40-32-000000,pB5ssSy__hBrm6wJ,rl2,4432.0,cup_on_saucer_success,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""green square saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-03-07-01-40-3...,,s3://rldb/processed_v3/aria/2026-03-07-01-40-3...,CC BY-SA 4.0,None

In [5]:
# Filter to certain lab
d1 = df[(df["task"] == "cup_on_saucer_static_cam") & (df["robot_name"] == "aria_bimanual") & (df["zarr_processed_path"].notna())]
print(len(d1))

d2 = df[(df["task"] == "cup_on_saucer_static_cam") & (df["robot_name"] == "aria_bimanual")]
print(len(d2))

24
24

In [6]:
d2

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
9678,2026-05-05-17-53-46-000000,Mengying,rl2,5619.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-17-53-4...,,s3://rldb/processed_v3/aria/2026-05-05-17-53-4...,NaN,None
9679,2026-05-05-17-34-59-000000,Mengying,rl2,6264.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-17-34-5...,,s3://rldb/processed_v3/aria/2026-05-05-17-34-5...,NaN,None
9680,2026-05-05-17-47-54-000000,Mengying,rl2,6022.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-17-47-5...,,s3://rldb/processed_v3/aria/2026-05-05-17-47-5...,NaN,None
9681,2026-05-05-17-41-27-000000,Mengying,rl2,6270.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-17-41-2...,,s3://rldb/processed_v3/aria/2026-05-05-17-41-2...,NaN,None
9683,2026-05-05-18-01-46-000000,Mengying,rl2,5897.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-18-01-4...,,s3://rldb/processed_v3/aria/2026-05-05-18-01-4...,NaN,None
9684,2026-05-05-18-46-06-000000,Mengying,rl2,4940.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""pink cup"",""white saucer"",""green saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-05-18-46-0...,,s3://rldb/processed_v3/aria/2026-05-05-18-46-0...,NaN,None
9792,2026-05-06-18-41-20-000000,Mengying,rl2,4838.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-41-2...,,s3://rldb/processed_v3/aria/2026-05-06-18-41-2...,NaN,None
9793,2026-05-06-18-18-02-000000,Mengying,rl2,5521.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-18-0...,,s3://rldb/processed_v3/aria/2026-05-06-18-18-0...,NaN,None
9794,2026-05-06-18-29-36-000000,Mengying,rl2,5462.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-29-3...,,s3://rldb/processed_v3/aria/2026-05-06-18-29-3...,NaN,None
9795,2026-05-06-18-23-28-000000,Mengying,rl2,5763.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-23-2...,,s3://rldb/processed_v3/aria/2026-05-06-18-23-2...,NaN,None
9796,2026-05-06-18-35-42-000000,Mengying,rl2,5555.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-35-4...,,s3://rldb/processed_v3/aria/2026-05-06-18-35-4...,NaN,None
9803,2026-05-06-18-57-32-000000,Mengying,rl2,3827.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-57-3...,,s3://rldb/processed_v3/aria/2026-05-06-18-57-3...,NaN,None
9804,2026-05-06-19-23-19-000000,Mengying,rl2,5755.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-23-1...,,s3://rldb/processed_v3/aria/2026-05-06-19-23-1...,NaN,None
9805,2026-05-06-18-47-43-000000,Mengying,rl2,5230.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-47-4...,,s3://rldb/processed_v3/aria/2026-05-06-18-47-4...,NaN,None
9806,2026-05-06-19-28-42-000000,Mengying,rl2,5826.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-28-4...,,s3://rldb/processed_v3/aria/2026-05-06-19-28-4...,NaN,None
9807,2026-05-06-18-53-03-000000,Mengying,rl2,4712.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-18-53-0...,,s3://rldb/processed_v3/aria/2026-05-06-18-53-0...,NaN,None
9810,2026-05-06-19-46-10-000000,Mengying,rl2,5717.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-46-1...,,s3://rldb/processed_v3/aria/2026-05-06-19-46-1...,NaN,None
9811,2026-05-06-19-39-57-000000,Mengying,rl2,5446.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-39-5...,,s3://rldb/processed_v3/aria/2026-05-06-19-39-5...,NaN,None
9812,2026-05-06-19-57-41-000000,Mengying,rl2,5196.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-57-4...,,s3://rldb/processed_v3/aria/2026-05-06-19-57-4...,NaN,None
9813,2026-05-06-19-52-20-000000,Mengying,rl2,5777.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-52-2...,,s3://rldb/processed_v3/aria/2026-05-06-19-52-2...,NaN,None
9814,2026-05-06-19-34-25-000000,Mengying,rl2,5479.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""pink cup"",""green square saucer"",...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-19-34-2...,,s3://rldb/processed_v3/aria/2026-05-06-19-34-2...,NaN,None
9818,2026-05-06-22-12-17-000000,Baoyu,rl2,4497.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""yellow saucer"",""white saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-22-12-1...,,s3://rldb/processed_v3/aria/2026-05-06-22-12-1...,NaN,None
9819,2026-05-06-22-18-40-000000,Baoyu,rl2,4325.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""yellow saucer"",""white saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-22-18-4...,,s3://rldb/processed_v3/aria/2026-05-06-22-18-4...,NaN,None
9820,2026-05-06-22-24-34-000000,Baoyu,rl2,4361.0,cup_on_saucer_static_cam,"pick up cup with one arm, hand it over to the ...",white_wall,"{""white cup"",""yellow saucer"",""white saucer""}",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2026-05-06-22-24-3...,,s3://rldb/processed_v3/aria/2026-05-06-22-24-3...,NaN,None

In [7]:
# Flagship Fold Clothes Data
df[(df["task"] == "fold_clothes") & df["lab"].isin(["rl2", "eth", "song", "wang"])]

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
70,2026-01-03-02-35-09-502000,4OOitkcdBEpTp3V5,rl2,787.0,fold_clothes,fold the t-shirt,1,"{""gray vneck t-shirt""}",s3://rldb/processed_v2/eva/2026-01-03-02-35-09...,rldb:/processed_v2/eva/1767407709502_video.mp4,...,eva_bimanual,False,-1.0,True,,s3://rldb/processed_v3/eva/2026-01-03-02-35-09...,,s3://rldb/processed_v3/eva/2026-01-03-02-35-09...,CC BY-SA 4.0,None
223,2025-10-14-04-15-30-000000,omDamnph0YxUBJSO,rl2,2888.0,fold_clothes,folding clothes,10,"{""short sleeve shirts"",""long sleeve shirts"",sh...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-10-14-04-15-3...,,s3://rldb/processed_v3/aria/2025-10-14-04-15-3...,CC BY-SA 4.0,None
233,2025-10-14-03-46-49-000000,omDamnph0YxUBJSO,rl2,3204.0,fold_clothes,folding clothes,16,"{""short sleeve shirts"",""long sleeve shirts"",sh...",,,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-10-14-03-46-4...,,s3://rldb/processed_v3/aria/2025-10-14-03-46-4...,CC BY-SA 4.0,None
287,2025-12-31-20-34-16-063000,4OOitkcdBEpTp3V5,rl2,1496.0,fold_clothes,fold the t-shirt,1,"{""white medium t-shirt""}",s3://rldb/processed_v2/eva/2025-12-31-20-34-16...,rldb:/processed_v2/eva/1767213256063_video.mp4,...,eva_bimanual,False,-1.0,True,,,,,CC BY-SA 4.0,None
374,2026-04-17-21-20-29-581000,19,rl2,-1.0,fold_clothes,fold the blue shirt,17,"{""blue shirt""}",,,...,eva_bimanual,False,-1.0,True,,,Zero Frames,,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71171,2025-11-11-22-55-28-353000,rl2,rl2,1567.0,fold_clothes,folding clothes,8,"{""short sleeve shirts"",""long sleeve shirts"",sh...",s3://rldb/processed_v2/aria/2025-11-11-22-55-2...,s3://rldb/processed_v2/aria/1762901728353_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-11-11-22-55-2...,,s3://rldb/processed_v3/aria/2025-11-11-22-55-2...,CC BY-SA 4.0,None
71172,2025-11-11-22-41-52-671000,wang,wang,2605.0,fold_clothes,folding clothes,7,{/coc/cedarp-dxu345-0/datasets/egoverse/old_da...,s3://rldb/processed_v2/aria/2025-11-11-22-41-5...,s3://rldb/processed_v2/aria/1762900912671_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-11-11-22-41-5...,,s3://rldb/processed_v3/aria/2025-11-11-22-41-5...,CC BY-SA 4.0,None
71173,2025-11-11-23-02-37-422000,song,song,3511.0,fold_clothes,folding clothes,5,"{""short sleeve shirts"",""long sleeve shirts"",sh...",s3://rldb/processed_v2/aria/2025-11-11-23-02-3...,s3://rldb/processed_v2/aria/1762902157422_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-11-11-23-02-3...,,s3://rldb/processed_v3/aria/2025-11-11-23-02-3...,CC BY-SA 4.0,None
71174,2025-11-11-23-00-10-404000,song,song,4013.0,fold_clothes,folding clothes,4,"{""short sleeve shirts"",""long sleeve shirts"",sh...",s3://rldb/processed_v2/aria/2025-11-11-23-00-1...,s3://rldb/processed_v2/aria/1762902010404_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-11-11-23-00-1...,,s3://rldb/processed_v3/aria/2025-11-11-23-00-1...,CC BY-SA 4.0,None
71311,2025-10-29-21-54-36-216000,CizpI2XpvnTL3SW5,rl2,-1.0,fold_clothes,folding clothes,1,"{""short sleeve shirts"",""long sleeve shirts"",sh...",s3://rldb/processed_v2/aria/2025-10-29-21-54-3...,s3://rldb/processed_v2/aria/1761774876216_vide...,...,aria_bimanual,False,-1.0,True,,,NameError: name 'zarr_processed_path' is not d...,,CC BY-SA 4.0,None

In [7]:
df[(df["task"] == "put cup on saucer indomain") & (df["lab"] == "rl2")]

,episode_hash,operator,lab,num_frames,task,task_description,scene,objects,processed_path,mp4_path,...,robot_name,is_eval,eval_score,eval_success,processing_error,zarr_processed_path,zarr_processing_error,zarr_mp4_path,license,segments
6131,2025-12-30-22-36-47-598000,cbb43DO-bmnqDXr5,rl2,4043.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134207598_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
6144,2025-12-30-22-36-45-830000,cbb43DO-bmnqDXr5,rl2,3834.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134205830_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
6156,2025-12-30-22-36-39-676000,cbb43DO-bmnqDXr5,rl2,3709.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134199676_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
8441,2025-12-27-22-25-17-000000,cbb43DO-bmnqDXr5,rl2,3781.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-27-22-25-1...,rldb:/processed_v2/aria/1766874317000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-22-25-1...,,s3://rldb/processed_v3/aria/2025-12-27-22-25-1...,CC BY-SA 4.0,None
24244,2025-12-30-22-36-38-823000,cbb43DO-bmnqDXr5,rl2,3700.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134198823_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
27094,2025-12-30-22-36-42-192000,cbb43DO-bmnqDXr5,rl2,3788.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""pink cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134202192_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27112,2025-12-27-21-34-49-000000,cbb43DO-bmnqDXr5,rl2,4368.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-27-21-34-4...,s3://rldb/processed_v2/aria/1766871289000_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-21-34-4...,,s3://rldb/processed_v3/aria/2025-12-27-21-34-4...,CC BY-SA 4.0,None
27360,2025-12-30-22-36-37-726000,cbb43DO-bmnqDXr5,rl2,3987.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134197726_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
27382,2025-12-30-22-36-44-662000,cbb43DO-bmnqDXr5,rl2,3757.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134204662_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27383,2025-12-30-22-36-49-222000,cbb43DO-bmnqDXr5,rl2,3816.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134209222_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27621,2025-12-27-22-19-52-000000,cbb43DO-bmnqDXr5,rl2,3938.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-27-22-19-5...,rldb:/processed_v2/aria/1766873992000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-22-19-5...,,s3://rldb/processed_v3/aria/2025-12-27-22-19-5...,CC BY-SA 4.0,None
27622,2025-12-30-22-36-47-420000,cbb43DO-bmnqDXr5,rl2,3934.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134207420_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27624,2025-12-30-22-36-47-431000,cbb43DO-bmnqDXr5,rl2,3977.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134207431_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27630,2025-12-30-22-36-48-174000,cbb43DO-bmnqDXr5,rl2,3925.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134208174_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
27631,2025-12-30-22-36-29-219000,cbb43DO-bmnqDXr5,rl2,3734.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-2...,rldb:/processed_v2/aria/1767134189219_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-2...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-2...,CC BY-SA 4.0,None
27633,2025-12-30-22-36-32-207000,cbb43DO-bmnqDXr5,rl2,3728.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134192207_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
27638,2025-12-30-22-36-51-011000,cbb43DO-bmnqDXr5,rl2,4100.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-5...,rldb:/processed_v2/aria/1767134211011_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-5...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-5...,CC BY-SA 4.0,None
28096,2025-12-30-22-36-25-849000,cbb43DO-bmnqDXr5,rl2,3876.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-2...,rldb:/processed_v2/aria/1767134185849_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-2...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-2...,CC BY-SA 4.0,None
28152,2025-12-27-21-52-58-000000,cbb43DO-bmnqDXr5,rl2,3817.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-27-21-52-5...,rldb:/processed_v2/aria/1766872378000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-21-52-5...,,s3://rldb/processed_v3/aria/2025-12-27-21-52-5...,CC BY-SA 4.0,None
28188,2025-12-30-22-36-51-340000,cbb43DO-bmnqDXr5,rl2,3723.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""pink cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-5...,rldb:/processed_v2/aria/1767134211340_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-5...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-5...,CC BY-SA 4.0,None
28197,2025-12-30-22-36-46-144000,cbb43DO-bmnqDXr5,rl2,4088.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134206144_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
28552,2025-12-30-22-36-47-982000,cbb43DO-bmnqDXr5,rl2,4113.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134207982_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
28575,2025-12-27-21-46-40-000000,cbb43DO-bmnqDXr5,rl2,4028.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-27-21-46-4...,s3://rldb/processed_v2/aria/1766872000000_vide...,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-21-46-4...,,s3://rldb/processed_v3/aria/2025-12-27-21-46-4...,CC BY-SA 4.0,None
28634,2025-12-30-22-36-48-502000,cbb43DO-bmnqDXr5,rl2,3770.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134208502_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
28643,2025-12-30-22-36-40-177000,cbb43DO-bmnqDXr5,rl2,3799.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134200177_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
28648,2025-12-30-22-36-38-569000,cbb43DO-bmnqDXr5,rl2,3702.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134198569_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
28649,2025-12-27-21-38-47-000000,cbb43DO-bmnqDXr5,rl2,3876.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-27-21-38-4...,rldb:/processed_v2/aria/1766871527000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-21-38-4...,,s3://rldb/processed_v3/aria/2025-12-27-21-38-4...,CC BY-SA 4.0,None
28709,2025-12-27-23-09-11-000000,cbb43DO-bmnqDXr5,rl2,4473.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-27-23-09-1...,rldb:/processed_v2/aria/1766876951000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-23-09-1...,,s3://rldb/processed_v3/aria/2025-12-27-23-09-1...,CC BY-SA 4.0,None
28743,2025-12-27-23-04-23-000000,cbb43DO-bmnqDXr5,rl2,3938.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-27-23-04-2...,rldb:/processed_v2/aria/1766876663000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-23-04-2...,,s3://rldb/processed_v3/aria/2025-12-27-23-04-2...,CC BY-SA 4.0,None
28766,2025-12-27-22-37-58-000000,cbb43DO-bmnqDXr5,rl2,3998.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-27-22-37-5...,rldb:/processed_v2/aria/1766875078000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-22-37-5...,,s3://rldb/processed_v3/aria/2025-12-27-22-37-5...,CC BY-SA 4.0,None
28791,2025-12-30-22-36-37-295000,cbb43DO-bmnqDXr5,rl2,3774.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134197295_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
28834,2025-12-27-22-15-54-000000,cbb43DO-bmnqDXr5,rl2,3828.0,put cup on saucer indomain,"pick up cup with one arm, hand it over to the ...",1,"{""pink cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-27-22-15-5...,rldb:/processed_v2/aria/1766873754000_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-27-22-15-5...,,s3://rldb/processed_v3/aria/2025-12-27-22-15-5...,CC BY-SA 4.0,None
28854,2025-12-30-22-36-39-111000,cbb43DO-bmnqDXr5,rl2,3771.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""white saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134199111_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None
31130,2025-12-30-22-36-45-808000,cbb43DO-bmnqDXr5,rl2,3719.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""green square saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134205808_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
31131,2025-12-30-22-36-45-156000,cbb43DO-bmnqDXr5,rl2,3864.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white ceramic cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-4...,rldb:/processed_v2/aria/1767134205156_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-4...,CC BY-SA 4.0,None
31469,2025-12-30-22-36-36-467000,cbb43DO-bmnqDXr5,rl2,3465.0,put cup on saucer indomain,"pick cup with one arm, hand it to the other ar...",1,"{""white cup"",""yellow saucer""}",s3://rldb/processed_v2/aria/2025-12-30-22-36-3...,rldb:/processed_v2/aria/1767134196467_video.mp4,...,aria_bimanual,False,-1.0,True,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,,s3://rldb/processed_v3/aria/2025-12-30-22-36-3...,CC BY-SA 4.0,None